name: Hello Workflow

on:
  push:

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: check the date and time
        run: echo date
      
      - name: Print brnach name
        run: echo "Branch: ${{ github.ref_name }}"
      

      - name: List files
        run: ls -la
     
      - name: Print runner oS
        run: echo "Runner OS: $RUNNER_OS"
