name: Secret Check

on:
  push:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether secret exists
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Try to print secret directly
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"
