name: PR Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR branch name
        run: 'echo "PR check running for branch: ${{ github.head_ref }}"'
