name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment name'
        required: true
        default: 'staging'

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment input
        run: 'echo "Environment selected: ${{ github.event.inputs.environment }}"'
